### ISSUE TITLE
Abnormal graphic interface

### ISSUE THREAD

**Issue by picayunesky** [Symb1OS/blackdesert-fishbot#1]
https://i.imgur.com/IxLzoXJ.png
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at java.util.Hashtable.get(Unknown Source)
        at javax.swing.UIDefaults.getFromHashtable(Unknown Source)
        at javax.swing.UIDefaults.get(Unknown Source)
        at javax.swing.MultiUIDefaults.get(Unknown Source)
        at javax.swing.UIDefaults.getString(Unknown Source)
        at javax.swing.UIManager.getString(Unknown Source)
        at ru.namibios.arduino.gui.view.SettingsView.<init>(SettingsView.java:109)
        at ru.namibios.arduino.gui.controller.SettingsController.actionPerformed(SettingsController.java:12)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by picayunesky** [comment]
@Symb1OS  yes. But have a new problem
`13.07.2018 19:03:37] - Start...
13.07.2018 19:03:40] - Port is open...
13.07.2018 19:03:44] - Start Fish...
13.07.2018 19:03:44] - Sended message[5]: space
13.07.2018 19:03:49] - Reseived a private message. Send telegram notification.
13.07.2018 19:03:51] - Received a private message. Switch to autofish...
13.07.2018 19:03:53] - Port closed...
13.07.2018 19:03:53] - Thread stop.
`
why port closed, is this a hardware problem?

**Comment by Symb1OS** [comment]
No, in your case he sees the text in the chat, takes them for a personal message and switches the mode to auto-fishing, and then turns off.

Check your settings.
You need to switch the item `Wrote pm:` to `nothing`.

**Comment by Symb1OS** [comment]
Notice:
Bot correctly working in RU server.

For correctly working in another server need modify.

**Comment by picayunesky** [comment]
@Symb1OS 
 THX :)
