### ISSUE TITLE
About Java some question

### ISSUE THREAD

**Issue by Kuruk-adm** [Symb1OS/blackdesert-fishbot#61]
Dear Symb1OS,

About: Blackdesert-fishbot
Java: jdk1.8.0_212
Bot: Last version bot

I launch build.bat happened some issue,
Can you help me fix this issue?
and this bot support other server?

Output:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.codehaus.plexus.classworlds.launcher.Launcher.getEnhancedMainMethod(Launcher.java:172)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:268)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 17 more

Looking forward to your reply, Thanks.

BR,
K

**Comment by Symb1OS** [comment]
Hello,

> I launch build.bat happened some issue,
Can you help me fix this issue?

Need update java to[ version 13](https://www.oracle.com/technetwork/java/javase/downloads/jdk13-downloads-5672538.html). [Guide](https://java.tutorials24x7.com/blog/how-to-install-java-13-on-windows)

> and this bot support other server?

Bot checked only on RU and EU server.
