### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by rezor7** [Symb1OS/blackdesert-fishbot#74]
Сервер RU, настройки все из wiki, версия 3.0.0 , самая последняя скачанная с релиза.
При ловле в море, какую бы рыбу не тянул появляется ошибка.

`[14.06.2021 09:58:17] - Check loot...
[14.06.2021 09:58:17] - Init filter
[14.06.2021 09:58:17] - Loot types: UNKNOWN,UNKNOWN,UNKNOWN,EMPTY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,
[14.06.2021 09:58:17] - Error java.lang.NullPointerException. Details in error.log`

`[14.06.2021 09:58:17] - java.lang.NullPointerException
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.bot.command.FishLoot.getLootFrames(FishLoot.java:114)
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.bot.command.FishLoot.getKey(FishLoot.java:177)
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.bot.service.input.EmulationService.send(EmulationService.java:177)
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.bot.state.FilterLootState.onStep(FilterLootState.java:26)
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.bot.state.State.process(State.java:82)
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.cli.Bot.process(Bot.java:62)
	at bdofishbot.bot@3.0.0/ru.namibios.bdofishbot.cli.Bot.run(Bot.java:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
`

Файлы прикрепил.

Как исправить?

[blackdesert-fishbot_3.0.0.zip](https://github.com/Symb1OS/blackdesert-fishbot/files/6646167/blackdesert-fishbot_3.0.0.zip)

**Comment by Symb1OS** [comment]
Скорее всего окно лута находится не на дефолтных позициях. Чтобы в этом убедиться в `application.properties` надо установить `bot.screen.debug.filterloot` в `true`. После чего запуститть и дать поработать.
В директорию `debug` будут сохраняться скрины, что он видит на месте лута.

Ну или как вариант сбросить все настройки интерфейса, чтобы все окна были на дефолтных позициях.

**Comment by Symb1OS** [comment]
Плюс пока лучше не использовать `скип календаря`, в этой версии он некорректно работает, может повлиять на правильную работу бота. В след версии будет исправлен.

**Comment by Symb1OS** [comment]
Либо в `application.properties` заменить  на следующие строчки:

`bot.screen.loot_slot_list=1412, 622, 42, 42;1466, 622, 42, 42;1520, 622, 42, 42;1574, 622, 42, 42;1628, 622, 42, 42;1682, 622, 42, 42;1412, 676, 42, 42;1466, 676, 42, 42`

`bot.screen.loot_slot_list.color=1411, 621, 45, 1;1465, 621, 45, 1;1519, 621, 45, 1;1573, 621, 45, 1;1627, 621, 45, 1;1681, 621, 45, 1;1411, 675, 45, 1;1465, 675, 45, 1`
